# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-13 00:22
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agenda', '0004_auto_20160212_0123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentType', models.CharField(choices=[(b'CPF', b'Cadastro Pessoa F\xc3\xadsica'), (b'RG', b'Carteira de Identidade'), (b'CNH', b'Carteira Nacional de Habilita\xc3\xa7\xc3\xa3o')], default=b'CPF', max_length=3)),
                ('documentNumber', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HealthProfessional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneType', models.CharField(choices=[(b'CEL', b'Celular'), (b'RES', b'Residencial'), (b'COM', b'Comercial')], default=b'CEL', max_length=3)),
                ('phoneNumber', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='firstName',
            field=models.CharField(default=datetime.datetime(2016, 2, 13, 0, 21, 36, 584482, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='foneticName',
            field=models.CharField(default='name', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='surname',
            field=models.CharField(default='surname', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phone',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Person'),
        ),
        migrations.AddField(
            model_name='healthprofessional',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='agenda.Person'),
        ),
        migrations.AddField(
            model_name='healthprofessional',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Person'),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together=set([('documentType', 'person')]),
        ),
    ]
